Update autoDeploy.yml
changed docker compose installation

diff --git a/.github/workflows/autoDeploy.yml b/.github/workflows/autoDeploy.yml
--- a/.github/workflows/autoDeploy.yml
+++ b/.github/workflows/autoDeploy.yml
@@ -30,12 +30,18 @@ jobs:
     - name: Install SSH client 
       run: sudo apt-get update && sudo apt-get install -y sshpass
 
-# Install Docker Compose
+    # Install Docker Compose
     - name: Install Docker Compose
       run: |
-        sudo curl -L "https://github.com/docker/compose/releases/download/2.12.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
-        sudo chmod +x /usr/local/bin/docker-compose
-        docker-compose --version
+        COMPOSE_URL="https://github.com/docker/compose/releases/download/2.12.2/docker-compose-$(uname -s)-$(uname -m)"
+        sudo curl -L "$COMPOSE_URL" -o /usr/local/bin/docker-compose
+        if file /usr/local/bin/docker-compose | grep -q "executable"; then
+          sudo chmod +x /usr/local/bin/docker-compose
+          docker-compose --version
+        else
+          echo "Docker Compose download failed"
+          exit 1
+        fi
         
     - name: SSH and deploy
       env:
